### ISSUE TITLE
model enable folder & checkpoints

### ISSUE THREAD

**Issue by haleqiu** [RUBNSUN/SFSNet#1]
What's the meaning of 
/tmp/SFSNet/checkpoints/sfsnet_checkpoints

in models/lastest
The checkpoints should be stored in tmp files?

**Comment by rubelchowdhury20** [comment]
Checkpoints from all the epochs will be saved in the tmp folder. As it will consume a lot of memory, you can delete it later if you want.
Only the latest checkpoints will be saved in the models/latest directory.
